/*Generated by WaveMaker Studio*/
package com.hrdb.service;

/*This is a Studio Managed File. DO NOT EDIT THIS FILE. Your changes may be reverted by Studio.*/

import java.io.OutputStream;

import org.springframework.data.domain.Page;
import org.springframework.data.domain.Pageable;

import com.wavemaker.runtime.data.export.ExportOptions;

import com.hrdb.models.query.*;

public interface HrdbQueryExecutorService {

    Page<QueryvarResponse> executeQueryvar(Pageable pageable);

    void exportQueryvar(ExportOptions exportOptions, Pageable pageable, OutputStream outputStream);

}