/*Generated by WaveMaker Studio*/
package com.alltypeservsforservdefs_9_0_0_1.classicmodels.service;

/*This is a Studio Managed File. DO NOT EDIT THIS FILE. Your changes may be reverted by Studio.*/


import org.slf4j.Logger;
import org.slf4j.LoggerFactory;
import org.springframework.beans.factory.annotation.Autowired;
import org.springframework.beans.factory.annotation.Qualifier;
import org.springframework.stereotype.Service;

import com.wavemaker.runtime.data.dao.query.WMQueryExecutor;

@Service
public class ClassicmodelsQueryExecutorServiceImpl implements ClassicmodelsQueryExecutorService {

    private static final Logger LOGGER = LoggerFactory.getLogger(ClassicmodelsQueryExecutorServiceImpl.class);

    @Autowired
    @Qualifier("classicmodelsWMQueryExecutor")
    private WMQueryExecutor queryExecutor;


}