/*Generated by WaveMaker Studio*/
package com.alltypeservsforservdefs_9_0_0_1.classicmodels.service;

/*This is a Studio Managed File. DO NOT EDIT THIS FILE. Your changes may be reverted by Studio.*/


import com.alltypeservsforservdefs_9_0_0_1.classicmodels.models.procedure.*;

public interface ClassicmodelsProcedureExecutorService {

    EmployeeProcVarResponse executeEmployeeProcVar();

}