/*Generated by WaveMaker Studio*/
package com.alltypeservsforservdefs_9_0_0_1.classicmodels.service;

/*This is a Studio Managed File. DO NOT EDIT THIS FILE. Your changes may be reverted by Studio.*/

import java.util.HashMap;
import java.util.Map;

import org.slf4j.Logger;
import org.slf4j.LoggerFactory;
import org.springframework.beans.factory.annotation.Autowired;
import org.springframework.beans.factory.annotation.Qualifier;
import org.springframework.stereotype.Service;
import org.springframework.transaction.annotation.Transactional;

import com.wavemaker.runtime.data.dao.procedure.WMProcedureExecutor;

import com.alltypeservsforservdefs_9_0_0_1.classicmodels.models.procedure.*;

@Service
public class ClassicmodelsProcedureExecutorServiceImpl implements ClassicmodelsProcedureExecutorService {

    private static final Logger LOGGER = LoggerFactory.getLogger(ClassicmodelsProcedureExecutorServiceImpl.class);

    @Autowired
    @Qualifier("classicmodelsWMProcedureExecutor")
    private WMProcedureExecutor procedureExecutor;

    @Transactional(value = "classicmodelsTransactionManager")
    @Override
    public EmployeeProcVarResponse executeEmployeeProcVar() {
        Map<String, Object> params = new HashMap<>(0);


        return procedureExecutor.executeNamedProcedure("EmployeeProcVar", params, EmployeeProcVarResponse.class);
    }

}