/*Generated by WaveMaker Studio*/
package com.hrdb.models.query;

/*This is a Studio Managed File. DO NOT EDIT THIS FILE. Your changes may be reverted by Studio.*/


import java.io.Serializable;
import java.util.Objects;

import com.fasterxml.jackson.annotation.JsonProperty;
import com.wavemaker.runtime.data.annotations.ColumnAlias;

public class QueryvarResponse implements Serializable {


    @JsonProperty("PASSWORD")
    @ColumnAlias("PASSWORD")
    private String password;

    @JsonProperty("ROLE")
    @ColumnAlias("ROLE")
    private String role;

    @JsonProperty("TENANT_ID")
    @ColumnAlias("TENANT_ID")
    private Integer tenantId;

    @JsonProperty("USERNAME")
    @ColumnAlias("USERNAME")
    private String username;

    @JsonProperty("USER_ID")
    @ColumnAlias("USER_ID")
    private Integer userId;

    public String getPassword() {
        return this.password;
    }

    public void setPassword(String password) {
        this.password = password;
    }

    public String getRole() {
        return this.role;
    }

    public void setRole(String role) {
        this.role = role;
    }

    public Integer getTenantId() {
        return this.tenantId;
    }

    public void setTenantId(Integer tenantId) {
        this.tenantId = tenantId;
    }

    public String getUsername() {
        return this.username;
    }

    public void setUsername(String username) {
        this.username = username;
    }

    public Integer getUserId() {
        return this.userId;
    }

    public void setUserId(Integer userId) {
        this.userId = userId;
    }

    @Override
    public boolean equals(Object o) {
        if (this == o) return true;
        if (!(o instanceof QueryvarResponse)) return false;
        final QueryvarResponse queryvarResponse = (QueryvarResponse) o;
        return Objects.equals(getPassword(), queryvarResponse.getPassword()) &&
                Objects.equals(getRole(), queryvarResponse.getRole()) &&
                Objects.equals(getTenantId(), queryvarResponse.getTenantId()) &&
                Objects.equals(getUsername(), queryvarResponse.getUsername()) &&
                Objects.equals(getUserId(), queryvarResponse.getUserId());
    }

    @Override
    public int hashCode() {
        return Objects.hash(getPassword(),
                getRole(),
                getTenantId(),
                getUsername(),
                getUserId());
    }
}