/*Generated by WaveMaker Studio*/
package com.alltypeservsforservdefs_9_0_0_1.classicmodels.models.procedure;

/*This is a Studio Managed File. DO NOT EDIT THIS FILE. Your changes may be reverted by Studio.*/


import java.io.Serializable;
import java.util.List;
import java.util.Objects;

import com.wavemaker.runtime.data.annotations.ColumnAlias;

public class EmployeeProcVarResponseContent implements Serializable {


    @ColumnAlias("employeeNumber")
    private Integer employeeNumber;

    @ColumnAlias("lastName")
    private String lastName;

    @ColumnAlias("firstName")
    private String firstName;

    @ColumnAlias("email")
    private String email;

    @ColumnAlias("extension")
    private String extension;

    @ColumnAlias("jobTitle")
    private String jobTitle;

    public Integer getEmployeeNumber() {
        return this.employeeNumber;
    }

    public void setEmployeeNumber(Integer employeeNumber) {
        this.employeeNumber = employeeNumber;
    }

    public String getLastName() {
        return this.lastName;
    }

    public void setLastName(String lastName) {
        this.lastName = lastName;
    }

    public String getFirstName() {
        return this.firstName;
    }

    public void setFirstName(String firstName) {
        this.firstName = firstName;
    }

    public String getEmail() {
        return this.email;
    }

    public void setEmail(String email) {
        this.email = email;
    }

    public String getExtension() {
        return this.extension;
    }

    public void setExtension(String extension) {
        this.extension = extension;
    }

    public String getJobTitle() {
        return this.jobTitle;
    }

    public void setJobTitle(String jobTitle) {
        this.jobTitle = jobTitle;
    }

    @Override
    public boolean equals(Object o) {
        if (this == o) return true;
        if (!(o instanceof EmployeeProcVarResponseContent)) return false;
        final EmployeeProcVarResponseContent employeeProcVarResponseContent = (EmployeeProcVarResponseContent) o;
        return Objects.equals(getEmployeeNumber(), employeeProcVarResponseContent.getEmployeeNumber()) &&
                Objects.equals(getLastName(), employeeProcVarResponseContent.getLastName()) &&
                Objects.equals(getFirstName(), employeeProcVarResponseContent.getFirstName()) &&
                Objects.equals(getEmail(), employeeProcVarResponseContent.getEmail()) &&
                Objects.equals(getExtension(), employeeProcVarResponseContent.getExtension()) &&
                Objects.equals(getJobTitle(), employeeProcVarResponseContent.getJobTitle());
    }

    @Override
    public int hashCode() {
        return Objects.hash(getEmployeeNumber(),
                getLastName(),
                getFirstName(),
                getEmail(),
                getExtension(),
                getJobTitle());
    }
}